apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: frensapp
type: Opaque
data:
  id_ed25519: {{ .Values.gitCredentials.id_ed25519 | b64enc }}
  id_ed25519.pub: {{ .Values.gitCredentials.id_ed25519_pub | b64enc }}
  known_hosts: {{ .Values.gitCredentials.known_hosts | b64enc }}
